# Используем официальный образ Node.js для работы с Next.js
FROM node:18

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и package-lock.json (или yarn.lock) в контейнер
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта в контейнер
COPY . .

# Собираем приложение Next.js для продакшн
RUN npm run build


# Открываем порт 3000
EXPOSE 3000

# Запускаем приложение в продакшн-режиме
CMD ["npm", "start"]
